### ISSUE TITLE
Thank you for the screenshots on the README

### ISSUE THREAD

**Issue by digital-raven** [aczw/sddm-theme-corners#10]
Thanks for the screenshots!

There's this other sddm theme suggested to me by Hyde-install called Candy but they didn't put screenshots up. Thanks for those it made choosing your code easy!

**Comment by aczw** [comment]
Thank you for the kind words! I've also gotten frustrated before when people don't put up screenshots in their README, especially for stuff like games or themes. Like, the product is literally something visual 💀
