### ISSUE TITLE
i did everything a incripted but all i get is a fallback theme 

### ISSUE THREAD

**Issue by Blanc3144** [aczw/sddm-theme-corners#12]
i am running arch hyprland with sddm which is currently using sweet theme and i was bored of it and wanted to try the corners and i installed corners but all i get to see is sddm's fallback theme i don't know where i got wrong please help

**Comment by aczw** [comment]
Thanks for trying this theme out! Could I get some more info? Did you create a `.conf` file in `/etc/sddm.conf.d` that sets the current theme to `corners`? Like this:

```
[Theme]
Current=corners
```

Call the file `theme-corners.conf` or something like that.

**Comment by Blanc3144** [comment]
yea i have a .conf file i changed the theme name and did everything

 `[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=corners

[Users]
MaximumUid=60513
MinimumUid=1000`

as you can see it didn't work at first but i found some helps on reddit, apparently changing the file name to kde_settings.conf makes sddm recognise its a config file. I don't know what others do but this trick works for me so i am fine with it

**Comment by aczw** [comment]
Okay, I'm glad that it was fixed either way! I really need to take a look at SDDM's rxnship with KDE and see if I need to update the theme on that front.... among many other things....
