### ISSUE TITLE
configuration to hide user avatar

### ISSUE THREAD

**Issue by vincent178** [aczw/sddm-theme-corners#3]
This is great theme, thanks for the work! I wonder is it able to hide the avatar image to make it even more cleaner? Thanks!

**Comment by aczw** [comment]
thank you!! sure, I can take a look and see what I can do... you're saying you want to disable this part, right?

![image](https://github.com/aczw/sddm-theme-corners/assets/79176651/e8c4d556-7811-424a-bbc8-4db65f4f17e5)

**Comment by vincent178** [comment]
Yes, exactly!!! ❤️

**Comment by aczw** [comment]
sorry, been busy with finals... will get on this asap

**Comment by vincent178** [comment]
@aczw no hurries, thanks!

**Comment by aczw** [comment]
@vincent178 go try it out!

**Comment by vincent178** [comment]
@aczw Thanks a lot, it works!!! One small issue though, if I use my old theme config, the locker screen would not render correctly, the background image is missing and the button don't have style either. After use the latest configuration, it will work as expected. I can share a screenshot after if this is helpful.

**Comment by aczw** [comment]
that's odd. please do send a screenshot! I changed some things in the new config, so that might be why. I think you'll have to port your old theme config to the new version.
