### ISSUE TITLE
Can't configure font

### ISSUE THREAD

**Issue by ghost** [aczw/sddm-theme-corners#5]
I am unable to configure the font-family through the theme.conf file. I have tried changing the font family, and then running $ sddm-greeter --test-mode --theme /usr/share/sddm/themes/corners: 
![image](https://github.com/aczw/sddm-theme-corners/assets/158471433/12e9a4f4-33f0-4e25-b63c-5c8101ac8e8c)

which works perfectly. Exactly as desired. But when I open the login-screen, the font doesn't change. 
![image](https://github.com/aczw/sddm-theme-corners/assets/158471433/035caf5a-3671-4a61-8bc6-3c19eb3d192c)

I am running hyprland(which I believe is the reason for the issue, being a wayland compositor) on arch. Any idea how I could resolve this issue?

**Comment by aczw** [comment]
hm... well, by default SDDM uses X11, but you can set it to [run on Wayland](https://wiki.archlinux.org/title/SDDM#Running_under_Wayland). since you're testing the greeter on hyprland (aka Wayland), maybe when it's actually running, the font family isn't being recognized on X11?

**Comment by ghost** [comment]
That did not seem to help whatsoever. I followed the steps shown on the wiki and downloaded weston. But the problem still persists

**Comment by aczw** [comment]
I would recommend running sddm on Xorg for now (that's what I'm doing, I log into a Wayland session and it works).

**Comment by ghost** [comment]
Yes well, I switched back to Xorg. Still, I can't identify what the issue with the font is.

**Comment by ghost** [comment]
Seems like the issue is fixed when I use a native x11 de. Still, thanks!
