### ISSUE TITLE
Sddm says I haven't installed QtGraphicalEFfects

### ISSUE THREAD

**Issue by ArchknightO-O** [aczw/sddm-theme-corners#9]
![2024-04-10-202349_hyprshot](https://github.com/aczw/sddm-theme-corners/assets/126905458/27e39af8-28ca-4823-a112-a154cadbd114)
^Screenshot of Sddm test

![2024-04-10-202730_hyprshot](https://github.com/aczw/sddm-theme-corners/assets/126905458/2bc57dce-884e-422c-9633-17b4532be663)
^Screenshot of output

I already ran the pacman command, so I'm not sure why it isn't working. Any help is wonderful!

**Comment by ArchknightO-O** [comment]
I have installed each package separately as well, I'm really not sure what the issue is.

**Comment by ArchknightO-O** [comment]
In the end what I had to do was remove the lines that called PowerPanel and UserPanel in the LoginPanel.qml file.

**Comment by Silzinc** [comment]
I was able to get it to work by replacing every `import QtGraphicalEffects` lines (in `UserPanel.qml`, `UserFieldPanel.qml` and `PowerPanel.qml`) with `import Qt5Compat.GraphicalEffects`, without specifying the version. I guess that solution is a bit better since it allows to keep the power button and user picture.

**Comment by aczw** [comment]
When I have more time, I would LOVE to update the theme to Qt6 and fix the bugs... I feel like that would resolve most of the issues

**Comment by Silzinc** [comment]
#17 There you go @aczw, though it might require some more testing (I have not done any QML in the past).

**Comment by aczw** [comment]
Thank you! I'm actually setting up a Linux machine soon so I'll try this out then.
